    /*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */
    package Interface.BanHang;

    import Models.Ban;
    import Mysql.ConnectSQL;

    import java.awt.Color;
    import java.awt.Dimension;
    import java.awt.event.MouseAdapter;
    import java.awt.event.MouseEvent;
    import java.util.ArrayList;
    import javax.swing.JButton;
    import javax.swing.border.Border;
    import javax.swing.border.LineBorder;

    public final class jpBanHang extends javax.swing.JPanel {
        ConnectSQL cn = new ConnectSQL();
        /**
         * Creates new form jpBanHang
         */
        ArrayList<Ban> arrBan;
        ArrayList<Ban> ban;
        int MaBan;
        public static jpBanHang bh;

        public jpBanHang() {
            initComponents();
            bh = this;
            FillBan();
//            jButton2.setBackground(Color.decode("#8080ff"));
//            jButton1.setBackground(Color.decode("#66ff66"));
//            jButton3.setBackground(Color.decode("#ff6699"));

        }


        /**
         *
         */
        public void fillLb() {
            jPanel2.removeAll();
            jPanel2.add(jLabel1);
            jPanel2.updateUI();
        }

        public void FillBan() {

            arrBan = cn.GetBan(0);
            if (arrBan != null) {
                jpBan.removeAll();
                JButton[] btn = new JButton[arrBan.size()];
                for (int i = 0; i < arrBan.size(); i++) {
                    btn[i] = new JButton();
                    btn[i].setName(String.valueOf(arrBan.get(i).GetMaBan()));
                    String[] mb = arrBan.get(i).GetTenBan().split(" ");
                    btn[i].setText(mb[1]);
                    btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/green-table.png")));
//                    btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/ico-Table.png")));

                      // Tạo thinkBorder 
                    Border thickBorder = new LineBorder(Color.WHITE, 8);
                    btn[i].setBorder(thickBorder);
//                    btn[i].setBackground(Color.decode("#8080ff"));
                    btn[i].setBackground(Color.WHITE);
                    btn[i].setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                    // 724F2B[114,79,43]
//                    btn[i].setForeground(new java.awt.Color(51, 51, 51));
                    btn[i].setForeground(new java.awt.Color(114, 79, 43));

                    if (arrBan.get(i).GetTrangThai().equals("Đang phục vụ")) {
                        btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/red-table.png"))); 
//                        btn[i].setBackground(Color.decode("#66ff66"));
                    }
                    if (arrBan.get(i).GetTrangThai().equals("Đã đặt trước")) {
                          btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/blue-table.png"))); 
//                        btn[i].setBackground(Color.decode("#ff6699"));
                        //btn[i].setBackground(Color.GREEN);
                    }
                    btn[i].setPreferredSize(new Dimension(90, 70));

                    btn[i].addMouseListener(new MouseAdapter() {
                        @Override
                        public void mousePressed(MouseEvent e) {
                            JpGoiMon goimon;
                            ban = cn.GetBan(Integer.parseInt(e.getComponent().getName()));
                            if (ban != null) {
                                goimon = new JpGoiMon(ban.get(0).GetTrangThai(), ban.get(0).GetTenBan(), ban.get(0).GetMaBan());
                                jPanel2.removeAll();
                                jPanel2.add(goimon);
                                jPanel2.updateUI();
                            }
                        }
                    });
                    jpBan.add(btn[i]);
                    jpBan.updateUI();
                }
            }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpBan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 519));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 519));
        jPanel2.setLayout(new java.awt.BorderLayout(200, 300));

        jLabel1.setMaximumSize(new java.awt.Dimension(580, 519));
        jLabel1.setMinimumSize(new java.awt.Dimension(580, 519));
        jLabel1.setPreferredSize(new java.awt.Dimension(580, 519));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpBan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(114, 79, 43));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/green-table.png"))); // NOI18N
        jLabel3.setText("Trống");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 79, 43));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/red-table.png"))); // NOI18N
        jLabel4.setText("Đang phục vụ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(114, 79, 43));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/blue-table.png"))); // NOI18N
        jLabel5.setText("Đã đặt trước");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpBan;
    // End of variables declaration//GEN-END:variables
    }
